compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: 0

nodeLinker: node-modules

npmRegistries:
  "//pkg.thdev.care":
    npmAlwaysAuth: true
    npmAuthIdent: "${THCARE_NPM_IDENT:-}"
npmScopes:
  thcare:
    npmRegistryServer: "https://pkg.thdev.care"

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
