compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  //pkg.th.care:
    npmAlwaysAuth: true
    npmAuthToken: "${THCARE_KEY:-}"

npmScopes:
  thcare:
    npmRegistryServer: "https://pkg.th.care"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
