compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  //pkg.thdev.care:
    npmAlwaysAuth: true
    npmAuthIdent: "${THCARE_KEY:-}"

npmScopes:
  thcare:
    npmRegistryServer: "https://pkg.thdev.care"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
