enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  //pkg.thdev.care:
    npmAlwaysAuth: true
    npmAuthIdent: "${THCARE_KEY:-}"

npmScopes:
  thcare:
    npmRegistryServer: "https://pkg.thdev.care"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
