compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: 0

nodeLinker: node-modules

npmRegistries:
  "//npm.pkg.github.com":
    # default the auth token to "" so that `yarn version` or `yarn lint` run successfully without any added permissions
    # anything that talks to the repository will fail with a confusing error message, unfortunately
    npmAuthToken: "${GITHUB_TOKEN:-}"

npmScopes:
  thcare:
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
