name: Deploy Solution
run-name: ${{ github.actor }} triggered a deploy
on: workflow_dispatch
concurrency: deploy-solution
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.THCARE_NODE_AUTH_TOKEN }}
        run: yarn install --mode=skip-build

      - name: Build
        run: yarn build

      - name: Package
        id: package
        env:
          GITHUB_TOKEN: ${{ secrets.THCARE_NODE_AUTH_TOKEN }}
        run: |
          yarn bundle
          echo "filename=$(pwd)/$(ls thcare-solution.tgz)" >> $GITHUB_OUTPUT

      - name: Build/Provision/Deploy
        uses: thcare/deploy.th.care/.github/actions/build-provision-deploy-solution@main
        with:
          client-name: ${{ vars.CLIENT_NAME }}
          build-environment: development
          deploy-environment: development
          dependency-token: ${{ secrets.THCARE_NODE_AUTH_TOKEN }}
          clone-token: ${{ secrets.THCARE_NODE_AUTH_TOKEN_V2 }}
          solution-package: ${{ steps.package.outputs.filename }}
          azure-subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
          azure-client-id: ${{ vars.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          provision-solution-api-key: ${{ secrets.PROVISION_SOLUTION_API_KEY }}
