name: Publish TH Care Framework Package

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release-action:
    runs-on: ubuntu-latest
    name: Release NPM Package
    needs: tests
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.THRIVEHEALTHBOT_PAT }}
        run: npx semantic-release
