name: Run tests

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: Pretty Quick
        run: npx pretty-quick --branch main --check
