name: Validate Pull Requests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate Solution
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn install --mode=skip-build

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint -- --max-warnings=0
