name: Validate Pull Requests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build Solution
        run: npm run build
